_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.0
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
            "3":
                - 16
                - 55
            "4": 3.10.0
            "5": 0.20.1
            "6": 4.52.4
            "8":
                - 3
            "12": 0.20.1
            "13": windows-amd64
model_name:
    value: Qwen/Qwen-VL-Chat
